### ISSUE TITLE
Not running locally

### ISSUE THREAD

**Issue by Niteesh-Kalangi** [SamProell/yarppg#18]
Whenever I try to run this locally, I run all the commands necessary, then run run-yarppg, and nothing happens. The program is running, but I don't see any results anywhere. I have had it running for 15 minutes straight and still nothing. If it matters, I am on MacOS, if that is an issue.
<img width="477" alt="image" src="https://github.com/user-attachments/assets/82ac89ac-0f08-4759-a467-67d866066d28">

**Comment by SamProell** [comment]
Which version of Python is this? This could be an issue with opencv or pyqt. I have seen some issues with this in newer versions of Python.

I have slowly been working towards an overhaul of the entire project, bringing it from the original Python 3.8 to 3.10+. 
If you want, you could try to test it out by checking out the yarppg1.0 branch. 

```bash
git checkout yarppg1.0
pip install -e ".[qt6]"
run-yarppg ui=qt6_simple
# or a simpler GUI, not depending on Qt:
run-yarppg ui=simplest   # or just run-yarppg
```

Note the README is not yet updated there, but you could consult docs/index.md.

**Comment by Niteesh-Kalangi** [comment]
Never mind, I got this to work by installing the correct versions
