### ISSUE TITLE
running on local device 

### ISSUE THREAD

**Issue by vyastanishq** [SamProell/yarppg#21]
hi i am currently running this project as per the following 

git clone https://github.com/SamProell/yarppg.git
cd yarppg
pip install "."
run-yarppg

and 

pip install ".[qt6]"
run-yarppg ui=qt6_simple

i want to run it on my local device on vscode so what to do and what are the steps to follow as there are a lot of files in the git repo available to download 

and also how to get that blue filter in the output as shown in the image in the repo

**Comment by vyastanishq** [comment]
and also any kind of neural network is used in this process ?

**Comment by SamProell** [comment]
sorry I do not quite understand what you mean by "running on local device", if `run-yarppg` already works.

If you want to use parts of yarPPG in your own code: this might help you get started: https://samproell.github.io/yarppg/deepdive/ or look at the code for the "simplest" UI here: https://github.com/SamProell/yarppg/blob/master/src/yarppg/ui/simplest.py

If its about starting the program through VS Code, you probably want to setup a launch configuration to start the `main.py` file: https://code.visualstudio.com/docs/python/debugging

**Comment by SamProell** [comment]
> and also any kind of neural network is used in this process ?

a neural network (https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/python) is used to detect the face. 
The default processor then only extracts the average green channel in the ROI. So nothing fancy in the processing part.

**Comment by SamProell** [comment]
> and also how to get that blue filter in the output as shown in the image in the repo

```bash
run-yarppg ui.roi_alpha=0.5
```

Some more information here: https://samproell.github.io/yarppg/cli/

**Comment by vyastanishq** [comment]
thank you

**Comment by vyastanishq** [comment]
hi i am suddenly getting DLL error from last night , (mediapipe related) so have you made any changes in the repo or is there any solution for it

**Comment by SamProell** [comment]
the code hasn't seen any changes since almost a month. If the problem persists, please open a new issue describing the error in more detail, what platform you are on and what version of python you are on.
