### ISSUE TITLE
modify data savepath 

### ISSUE THREAD

**Issue by Wessteros068** [SamProell/yarppg#25]
Can you help me to modify data collected in the savepath ? I'd like to save HR also in the save file ( I use the 0.1 version, the 1.0 is too slow for me, I have the problem with the QT6), many thanks

**Comment by SamProell** [comment]
Hi there, 
sorry for the late reply. Getting this working in 0.1 is not so straightforward, which is actually one of the reasons I re-wrote a lot of the old code. I also noticed performance is not so great on limited hardware and will look into this in the next days. As this is already implemented in 1.0, it would be best if you could just use this version without performance issues.

**Comment by SamProell** [comment]
@Wessteros068, after testing on an older laptop I think performance of the Qt6 UI in version 1.0 should be better for you as well. Would you mind testing with the latest changes and giving me feedback here? Could be the easiest fix for your issue.  - #24

**Comment by Wessteros068** [comment]
thank you @SamProell for your feedback, I maked a new script, and you are right QT6 gives better results.
